-- DEPARTMENTS (5 rows)
-- Column types inferred: {'DEPARTMENT_ID': 'number', 'DEPARTMENT_NAME': 'string', 'FLOOR_NO': 'number', 'STATUS': 'string'}

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, FLOOR_NO, STATUS) VALUES (1, 'Cardiology', 1, 'Active');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, FLOOR_NO, STATUS) VALUES (2, 'Pediatrics', 2, 'Active');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, FLOOR_NO, STATUS) VALUES (3, 'Emergency', 0, 'Active');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, FLOOR_NO, STATUS) VALUES (4, 'Orthopedics', 3, 'Active');
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, FLOOR_NO, STATUS) VALUES (5, 'General Medicine', 1, 'Active');

COMMIT;
