-- DOCTOR_SPECIALTIES (5 rows)
-- Column types inferred: {'SPECIALTY_ID': 'number', 'SPECIALTY_NAME': 'string', 'STATUS': 'string'}

INSERT INTO DOCTOR_SPECIALTIES (SPECIALTY_ID, SPECIALTY_NAME, STATUS) VALUES (1, 'Cardiologist', 'Active');
INSERT INTO DOCTOR_SPECIALTIES (SPECIALTY_ID, SPECIALTY_NAME, STATUS) VALUES (2, 'Pediatrician', 'Active');
INSERT INTO DOCTOR_SPECIALTIES (SPECIALTY_ID, SPECIALTY_NAME, STATUS) VALUES (3, 'Emergency Physician', 'Active');
INSERT INTO DOCTOR_SPECIALTIES (SPECIALTY_ID, SPECIALTY_NAME, STATUS) VALUES (4, 'Orthopedic Surgeon', 'Active');
INSERT INTO DOCTOR_SPECIALTIES (SPECIALTY_ID, SPECIALTY_NAME, STATUS) VALUES (5, 'General Practitioner', 'Active');

COMMIT;
