-- MEDICINE_CATEGORIES (5 rows)
-- Column types inferred: {'CATEGORY_ID': 'number', 'CATEGORY_NAME': 'string', 'STATUS': 'string'}

INSERT INTO MEDICINE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, STATUS) VALUES (1, 'Antibiotic', 'Active');
INSERT INTO MEDICINE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, STATUS) VALUES (2, 'Painkiller', 'Active');
INSERT INTO MEDICINE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, STATUS) VALUES (3, 'Diabetes', 'Active');
INSERT INTO MEDICINE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, STATUS) VALUES (4, 'Cardiovascular', 'Active');
INSERT INTO MEDICINE_CATEGORIES (CATEGORY_ID, CATEGORY_NAME, STATUS) VALUES (5, 'Vitamins', 'Active');

COMMIT;
