-- APPOINTMENT_STATUSES (4 rows)
-- Column types inferred: {'STATUS_ID': 'number', 'STATUS_NAME': 'string'}

INSERT INTO APPOINTMENT_STATUSES (STATUS_ID, STATUS_NAME) VALUES (3, 'Cancelled');
INSERT INTO APPOINTMENT_STATUSES (STATUS_ID, STATUS_NAME) VALUES (2, 'Completed');
INSERT INTO APPOINTMENT_STATUSES (STATUS_ID, STATUS_NAME) VALUES (4, 'No Show');
INSERT INTO APPOINTMENT_STATUSES (STATUS_ID, STATUS_NAME) VALUES (1, 'Scheduled');

COMMIT;
