-- DOCTORS (10 rows)
-- Column types inferred: {'DOCTOR_ID': 'number', 'FULL_NAME': 'string', 'DEPARTMENT_ID': 'number', 'SPECIALTY_ID': 'number', 'MOBILE_NO': 'number', 'EMAIL': 'string', 'CONSULTATION_FEE': 'number', 'STATUS': 'string'}

INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS) VALUES (21, 'Ahmed mostafa', 1, 3, 99994444, 'ahmed@hotmail.com', 55, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS) VALUES (22, 'Zakiya Alnabhani', 2, 2, 97234521, 'Zakiya@gmail.com', 14, 'Inactive');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS) VALUES (1, 'Mariya allamki', 3, 3, 92345676, 'admin@admin.com', 39, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS) VALUES (41, 'Dr. Ahmed Al Balushi', 1, 1, 92110001, 'ahmed.balushi@alnoorhospital.com', 25, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS) VALUES (42, 'Dr. Sara Al Hinai', 2, 2, 92110002, 'sara.hinai@alnoorhospital.com', 20, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS) VALUES (43, 'Dr. Mustafa Al Rawahi', 3, 3, 92110003, 'mustafa.rawahi@alnoorhospital.com', 30, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS) VALUES (44, 'Dr. Fatma Al Harthy', 4, 4, 92110004, 'fatma.harthy@alnoorhospital.com', 35, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS) VALUES (45, 'Dr. Khalid Al Amri', 5, 5, 92110005, 'khalid.amri@alnoorhospital.com', 18, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS) VALUES (46, 'Dr. Aisha Al Maamari', 1, 1, 92110006, 'aisha.maamari@alnoorhospital.com', 28, 'Active');
INSERT INTO DOCTORS (DOCTOR_ID, FULL_NAME, DEPARTMENT_ID, SPECIALTY_ID, MOBILE_NO, EMAIL, CONSULTATION_FEE, STATUS) VALUES (47, 'Dr. Omar Al Busaidi', 2, 2, 92110007, 'omar.busaidi@alnoorhospital.com', 22, 'Active');

COMMIT;
