-- MEDICINES (24 rows)
-- Column types inferred: {'MEDICINE_ID': 'number', 'MEDICINE_NAME': 'string', 'CATEGORY_ID': 'number', 'UNIT': 'string', 'CURRENT_STOCK': 'number', 'REORDER_LEVEL': 'number', 'STATUS': 'string'}

INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (21, 'Zenc +', 4, 'Capsule', 14, 4, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (41, 'Amoxicillin 500mg', 1, 'Capsule', 120, 30, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (42, 'Azithromycin 250mg', 1, 'Tablet', 45, 20, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (43, 'Cefuroxime 500mg', 1, 'Tablet', 18, 25, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (44, 'Metronidazole 400mg', 1, 'Tablet', 60, 20, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (45, 'Paracetamol 500mg', 2, 'Tablet', 200, 50, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (46, 'Ibuprofen 400mg', 2, 'Tablet', 75, 30, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (47, 'Diclofenac 50mg', 2, 'Tablet', 15, 20, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (48, 'Paracetamol Syrup', 2, 'Syrup', 40, 15, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (49, 'Metformin 500mg', 3, 'Tablet', 150, 40, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (50, 'Gliclazide 80mg', 3, 'Tablet', 55, 20, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (51, 'Insulin Regular', 3, 'Injection', 12, 15, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (52, 'Insulin Glargine', 3, 'Injection', 25, 10, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (53, 'Amlodipine 5mg', 4, 'Tablet', 90, 25, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (1, 'panadol', 4, 'Capsule', 6, 1, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (2, 'adol', 1, 'Syrup', 18, 2, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (22, 'messc', 3, 'Capsule', 20, 8, 'Inactive');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (54, 'Losartan 50mg', 4, 'Tablet', 70, 20, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (55, 'Atorvastatin 20mg', 4, 'Tablet', 22, 30, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (56, 'Bisoprolol 5mg', 4, 'Tablet', 50, 15, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (57, 'Vitamin D3 1000 IU', 5, 'Tablet', 110, 30, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (58, 'Vitamin C 500mg', 5, 'Tablet', 95, 25, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (59, 'Vitamin B Complex', 5, 'Tablet', 14, 20, 'Active');
INSERT INTO MEDICINES (MEDICINE_ID, MEDICINE_NAME, CATEGORY_ID, UNIT, CURRENT_STOCK, REORDER_LEVEL, STATUS) VALUES (60, 'Multivitamin Syrup', 5, 'Syrup', 35, 15, 'Active');

COMMIT;
