-- PRESCRIPTIONS (10 rows)
-- Column types inferred: {'PATIENT_ID': 'number', 'DOCTOR_ID': 'number', 'PRESCRIPTION_DATE': 'timestamp', 'NOTES': 'string', 'PRESCRIPTION_ID': 'number', 'VISIT_ID': 'number'}

INSERT INTO PRESCRIPTIONS (PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES, PRESCRIPTION_ID, VISIT_ID) VALUES (76, 41, TO_TIMESTAMP('2026-07-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Prescription issued during patient visit', 21, 21);
INSERT INTO PRESCRIPTIONS (PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES, PRESCRIPTION_ID, VISIT_ID) VALUES (77, 42, TO_TIMESTAMP('2026-07-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Prescription issued during patient visit', 22, 22);
INSERT INTO PRESCRIPTIONS (PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES, PRESCRIPTION_ID, VISIT_ID) VALUES (78, 43, TO_TIMESTAMP('2026-07-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Prescription issued during patient visit', 23, 23);
INSERT INTO PRESCRIPTIONS (PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES, PRESCRIPTION_ID, VISIT_ID) VALUES (79, 44, TO_TIMESTAMP('2026-07-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Prescription issued during patient visit', 24, 24);
INSERT INTO PRESCRIPTIONS (PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES, PRESCRIPTION_ID, VISIT_ID) VALUES (80, 45, TO_TIMESTAMP('2026-07-15 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Prescription issued during patient visit', 25, 25);
INSERT INTO PRESCRIPTIONS (PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES, PRESCRIPTION_ID, VISIT_ID) VALUES (81, 46, TO_TIMESTAMP('2026-07-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Prescription issued during patient visit', 26, 26);
INSERT INTO PRESCRIPTIONS (PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES, PRESCRIPTION_ID, VISIT_ID) VALUES (82, 47, TO_TIMESTAMP('2026-07-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Prescription issued during patient visit', 27, 27);
INSERT INTO PRESCRIPTIONS (PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES, PRESCRIPTION_ID, VISIT_ID) VALUES (83, 41, TO_TIMESTAMP('2026-07-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Prescription issued during patient visit', 28, 28);
INSERT INTO PRESCRIPTIONS (PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES, PRESCRIPTION_ID, VISIT_ID) VALUES (84, 42, TO_TIMESTAMP('2026-07-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Prescription issued during patient visit', 29, 29);
INSERT INTO PRESCRIPTIONS (PATIENT_ID, DOCTOR_ID, PRESCRIPTION_DATE, NOTES, PRESCRIPTION_ID, VISIT_ID) VALUES (85, 43, TO_TIMESTAMP('2026-07-16 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Prescription issued during patient visit', 30, 30);

COMMIT;
