-- PRESCRIPTION_ITEMS (10 rows)
-- Column types inferred: {'PRESCRIPTION_ITEM_ID': 'number', 'PRESCRIPTION_ID': 'number', 'MEDICINE_ID': 'number', 'DOSAGE': 'string', 'FREQUENCY': 'string', 'DURATION_DAYS': 'number', 'INSTRUCTIONS': 'string'}

INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS) VALUES (21, 21, 1, '250mg', 'Twice daily', 7, 'Take as directed by the doctor');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS) VALUES (22, 22, 2, '1 tablet', 'Three times daily', 10, 'Take as directed by the doctor');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS) VALUES (23, 23, 21, '5ml', 'Once daily', 5, 'Take as directed by the doctor');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS) VALUES (24, 24, 22, '500mg', 'Twice daily', 7, 'Take as directed by the doctor');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS) VALUES (25, 25, 41, '250mg', 'Three times daily', 10, 'Take as directed by the doctor');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS) VALUES (26, 26, 42, '1 tablet', 'Once daily', 5, 'Take as directed by the doctor');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS) VALUES (27, 27, 43, '5ml', 'Twice daily', 7, 'Take as directed by the doctor');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS) VALUES (28, 28, 44, '500mg', 'Three times daily', 10, 'Take as directed by the doctor');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS) VALUES (29, 29, 45, '250mg', 'Once daily', 5, 'Take as directed by the doctor');
INSERT INTO PRESCRIPTION_ITEMS (PRESCRIPTION_ITEM_ID, PRESCRIPTION_ID, MEDICINE_ID, DOSAGE, FREQUENCY, DURATION_DAYS, INSTRUCTIONS) VALUES (30, 30, 46, '1 tablet', 'Twice daily', 7, 'Take as directed by the doctor');

COMMIT;
